[2023-05-01T11:39:50.655+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T11:30:38.175260+00:00 [queued]>
[2023-05-01T11:39:50.660+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T11:30:38.175260+00:00 [queued]>
[2023-05-01T11:39:50.660+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T11:39:50.660+0000] {taskinstance.py:1289} INFO - Starting attempt 6 of 6
[2023-05-01T11:39:50.660+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T11:39:50.668+0000] {taskinstance.py:1309} INFO - Executing <Task(GCSFileTransformOperator): space_missions_launches_to_gcp_task> on 2023-05-01 11:30:38.175260+00:00
[2023-05-01T11:39:50.672+0000] {standard_task_runner.py:55} INFO - Started process 3016 to run task
[2023-05-01T11:39:50.674+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'space_missions_launches_to_gcp_dag', 'space_missions_launches_to_gcp_task', 'manual__2023-05-01T11:30:38.175260+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/space_missions_launches_to_gcp.py', '--cfg-path', '/tmp/tmpkovx73ps']
[2023-05-01T11:39:50.675+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask space_missions_launches_to_gcp_task
[2023-05-01T11:39:50.708+0000] {task_command.py:389} INFO - Running <TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T11:30:38.175260+00:00 [running]> on host e47d5c97588c
[2023-05-01T11:39:50.750+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=viktoria.k
AIRFLOW_CTX_DAG_ID=space_missions_launches_to_gcp_dag
AIRFLOW_CTX_TASK_ID=space_missions_launches_to_gcp_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T11:30:38.175260+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-01T11:30:38.175260+00:00
[2023-05-01T11:39:50.755+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-05-01T11:39:50.759+0000] {gcs.py:578} INFO - Downloading file from dataset_source_bucket
[2023-05-01T11:39:51.397+0000] {gcs.py:341} INFO - File downloaded to /tmp/tmpr5xenc0d
[2023-05-01T11:39:51.397+0000] {gcs.py:583} INFO - Starting the transformation
[2023-05-01T11:39:51.406+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py", line 587, in execute
    args=cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, close_fds=True
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/airflow/dags/utils/missions_launches_transformation_script.py': '/airflow/dags/utils/missions_launches_transformation_script.py'
[2023-05-01T11:39:51.413+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=space_missions_launches_to_gcp_dag, task_id=space_missions_launches_to_gcp_task, execution_date=20230501T113038, start_date=20230501T113950, end_date=20230501T113951
[2023-05-01T11:39:51.422+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task space_missions_launches_to_gcp_task ([Errno 2] No such file or directory: '/airflow/dags/utils/missions_launches_transformation_script.py': '/airflow/dags/utils/missions_launches_transformation_script.py'; 3016)
[2023-05-01T11:39:51.447+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-01T11:39:51.457+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
