[2023-05-01T14:00:28.484+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_from_gcs_to_bq_task manual__2023-05-01T14:00:25.211900+00:00 [queued]>
[2023-05-01T14:00:28.490+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_from_gcs_to_bq_task manual__2023-05-01T14:00:25.211900+00:00 [queued]>
[2023-05-01T14:00:28.490+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T14:00:28.490+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T14:00:28.490+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T14:00:28.503+0000] {taskinstance.py:1309} INFO - Executing <Task(GCSToBigQueryOperator): space_missions_launches_from_gcs_to_bq_task> on 2023-05-01 14:00:25.211900+00:00
[2023-05-01T14:00:28.509+0000] {standard_task_runner.py:55} INFO - Started process 9494 to run task
[2023-05-01T14:00:28.512+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'space_missions_launches_to_gcp_dag', 'space_missions_launches_from_gcs_to_bq_task', 'manual__2023-05-01T14:00:25.211900+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/space_missions_launches_to_gcp.py', '--cfg-path', '/tmp/tmpdt6c8i6g']
[2023-05-01T14:00:28.512+0000] {standard_task_runner.py:83} INFO - Job 38: Subtask space_missions_launches_from_gcs_to_bq_task
[2023-05-01T14:00:28.551+0000] {task_command.py:389} INFO - Running <TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_from_gcs_to_bq_task manual__2023-05-01T14:00:25.211900+00:00 [running]> on host e47d5c97588c
[2023-05-01T14:00:28.593+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=viktoria.k
AIRFLOW_CTX_DAG_ID=space_missions_launches_to_gcp_dag
AIRFLOW_CTX_TASK_ID=space_missions_launches_from_gcs_to_bq_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T14:00:25.211900+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-01T14:00:25.211900+00:00
[2023-05-01T14:00:28.598+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-05-01T14:00:28.602+0000] {gcs_to_bigquery.py:382} INFO - Using existing BigQuery table for storing data...
[2023-05-01T14:00:28.634+0000] {gcs_to_bigquery.py:386} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'de-camp-v1', 'datasetId': 'space_mission_launches', 'tableId': 'mission_launches'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://de-camp-v1_dl/mission_launches.csv'], 'writeDisposition': 'WRITE_EMPTY', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-05-01T14:00:28.634+0000] {bigquery.py:1546} INFO - Inserting job ***_space_missions_launches_to_gcp_dag_space_missions_launches_from_gcs_to_bq_task_2023_05_01T14_00_25_211900_00_00_db9ad0a874d089d0c4dfd9dbd85858a7
[2023-05-01T14:00:29.327+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 445, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.Conflict: 409 Already Exists: Table de-camp-v1:space_mission_launches.mission_launches
[2023-05-01T14:00:29.332+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=space_missions_launches_to_gcp_dag, task_id=space_missions_launches_from_gcs_to_bq_task, execution_date=20230501T140025, start_date=20230501T140028, end_date=20230501T140029
[2023-05-01T14:00:29.340+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 38 for task space_missions_launches_from_gcs_to_bq_task (409 Already Exists: Table de-camp-v1:space_mission_launches.mission_launches; 9494)
[2023-05-01T14:00:29.366+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-01T14:00:29.395+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
